# PyTorch Fundamentals
## 2. Variables with Gradients

### 2.1 Variables
<ul>
    <li>A Variable wraps a Tensor</li>
    <li>Allows accumulation of gradients</li>
</ul>

In [2]:
import torch
from torch.autograd import Variable

In [4]:
a = Variable(torch.ones(2, 2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [10]:
a.requires_grad

True

In [12]:
# Not a Variable:

no_variable = torch.ones(2, 2)
no_variable

tensor([[1., 1.],
        [1., 1.]])

In [13]:
no_variable.requires_grad

False

In [6]:
# Behaves similarly to Tensors:

b = Variable(torch.ones(2, 2), requires_grad = True)
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [8]:
print(a * b)
print(a.mul(b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


## 2.1 Gradients

### Creating Tensor with Gradients
- A Variable wraps a Tensor
- Allows accumulation of gradients

### Manually and Automatically Calculating Gradients

**What exactly is `requires_grad`?**
- Allows calculation of gradients w.r.t. the variable

$$y_i = 5(x_i+1)^2$$

In [16]:
x = torch.ones((2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

$$y_i\bigr\rvert_{x_i=1} = 5(1 + 1)^2 = 5(2)^2 = 5(4) = 20$$

In [17]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

**Backward should be called only on a scalar (i.e. 1-element tensor) or with gradient w.r.t. the variable**
- Let's reduce y to a scalar then...

$$o = \frac{1}{2}\sum_i y_i$$

In [18]:
o = (1/2) * torch.sum(y) #This is actually taking the mean of "y".
o

tensor(20., grad_fn=<MulBackward0>)

<center> **Recap `y` equation**: $y_i = 5(x_i+1)^2$ </center>

<center> **Recap `o` equation**: $o = \frac{1}{2}\sum_i y_i$ </center>

<center> **Substitute `y` into `o` equation**: $o = \frac{1}{2} \sum_i 5(x_i+1)^2$ </center>

$$\frac{\partial o}{\partial x_i} = \frac{1}{2}[10(x_i+1)]$$

$$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{1}{2}[10(1 + 1)] = \frac{10}{2}(2) = 10$$

In [19]:
o.backward()

In [20]:
x.grad

tensor([10., 10.])

In [24]:
# Backward in detail:

o.backward(torch.FloatTensor([1.0, 1.0]))
x.grad

tensor([10., 10.])

In [13]:
x.requires_grad

True

In [15]:
y.requires_grad

True

In [14]:
o.requires_grad

True

---
# Summary
- Tensor with Gradients
    - Wraps a tensor for gradient accumulation
- Gradients
    - Define original equation
    - Substitute equation with `x` values
    - Reduce to scalar output, `o` through `mean`
    - Calculate gradients with `o.backward()`
    - Then access gradients of the `x` variable through `x.grad`